version: '3'

services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: ffmpeg
    tty: true
    # stdin_open: true
    volumes:
       - /var/www/ffmpeg/node_modules