version: "3"

services:
  frontend:
    container_name: ffmpeg_frontend
    build: ./
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    # tty: true
    # stdin_open: true
    volumes:
      - ./:/var/www/app
      - ./node_modules:/var/www/app/node_modules
