version: "3"

services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    container_name: frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    volumes:
      - "./:/app"
      - "./:/app/node_modules"
